### ISSUE TITLE
Should I use Microsoft.Extensions.Logging.ILogger<T> or Serilog.ILogger?

### ISSUE THREAD

**Issue by Lindsey1986** [serilog/serilog-aspnetcore#104]
All examples of using Serilog with ASP .NET Core I see, are using Microsoft's logging interface, instead of Serilog's interface.

Is that the recommended approach now? If yes, why is that?

**Comment by Jehoel** [comment]
In all of my work, I only use types from the `Serilog.*` namespace in my Serilog configuration code - the rest of the project (controllers, other services, etc) all use `Microsoft.Extensions.Logging.ILogger<T>` - this makes them portable to other environments where Serilog might not be available.

Very rarely have I been wanting Serilog-specific functionality elsewhere in my codebase.

**Comment by nblumhardt** [comment]
I'm the opposite way around - I only set up the _Microsoft.Extensions.*_ interfaces so that the framework can have access to the logging pipeline. In application code, I use Serilog's `ILogger` and static `Log.*` methods exclusively.

In the end I think it's a matter of taste. I prefer the shorter method names and lack of generic type arguments in the Serilog interfaces.

I also dislike having to clutter every constructor with `ILogger<T>` parameters (constructor argument lists are highly-valuable real estate), and find there are usability issues once code steps out of DI and starts calling non-DI-instantiated classes that want to do some logging (more parameter passing).

YMMV!

Serilog is currently available in all environments supported by _Microsoft.Extensions.Logging_ that I'm aware of, plus several more. :-)

**Comment by Jehoel** [comment]
@nblumhardt 

> I also dislike having to clutter every constructor with ILogger<T> parameters (constructor argument lists are highly-valuable real estate), and find there are usability issues once code steps out of DI and starts calling non-DI-instantiated classes that want to do some logging (more parameter passing).

You can accept `ILoggerFactory` as a constructor parameter and use the generic call inside your ctor body instead of accepting a `ILogger<T>` directly - or even just `ILogger` if you don't care about having an automatically-generated `Category` value.

I use T4 for generating constructors for DI a lot, actually - which helps with the ergonomics of having more than a few constructor parameters. It's available here if you're interested: https://gist.github.com/Jehoel/f395a419e9d70c4a718284fdfeef007b

**Comment by Lindsey1986** [comment]
Thank you all. I'm going with Serilog's ILogger and static `Log.*` methods then.

**Comment by molinch** [comment]
@nblumhardt @Jehoel kind of related to the topic, I'd like to use Serilog ILogger because it has more capabilities, like enriching the information. For example I have an extension method:
```c#
public static ILogger Here(this ILogger logger, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0)
{
  return logger
    .ForContext("MemberName", memberName)
    .ForContext("FilePath", sourceFilePath)
    .ForContext("LineNumber", sourceLineNumber);
}
```

So I would like to use this while logging, like:
```c#
_logger.Here().Debug("this happened");
```
So that I know from where the log is coming from.

Unfortunately, as far as I know, I would require the Serilog ILogger, but `.UseSeriLog` only injects the ILoggerFactory.
Would you recommend to manually register Serilog ILogger to ASP.NET Core DI?

**Comment by sungam3r** [comment]
Do not forget that you can go the third way - do not use either the first or the second. Creating your own abstraction is a good option if you are going to build a large system with your own library stack. In this case, by creating your own dependency, you protect against possible problems when changing dependency versions. The specific implementation of logging is placed in a separate package. I mean implementation since `Serilog.ILogger` is not a just interface. Even if you use `ILogger`, you still make a dependency on the entire package (with the specific version) where the whole implementation is located.

**Comment by utsabshrestha** [comment]
How to use Serilog ILogger, can anyone show me the way ? Cause in every tutorial and all around , everybody are using Microsoft.Extensions.Logging.ILogger<T> and injecting ILogger to log. How to inject Serilog ILogger and use in other class?
@nblumhardt @Lindsey1986 @Jehoel

**Comment by Jehoel** [comment]
@utsabshrestha  You should ask that on StackOverflow

**Comment by bthulu** [comment]
@Jehoel why should ask on stackoverflow? it should be in document or wiki. it is a common use case, should not ask in stackoverflow.

**Comment by computersarecool** [comment]
Lucky for you all somebody already did ask it on [Stack Overflow](https://stackoverflow.com/q/61544047/3291506).
