### ISSUE TITLE
Unlock the assembly version

### ISSUE THREAD

**Issue by SimonCropp** [serilog/serilog-aspnetcore#119]
https://github.com/serilog/serilog-aspnetcore/blob/dev/src/Serilog.AspNetCore/Properties/AssemblyInfo.cs#L4

**Comment by nblumhardt** [comment]
It can probably be unlocked, now; this dates back to when binding redirects were causing misery. Less of an issue now, especially since new ASP.NET Core versions aren't targeting .NET Framework.

We still lock _Serilog_ at 2.0 as well, though since it will go on supporting .NET Framework for a lot longer - indefinitely at this stage - we might keep that one locked.

**Comment by SimonCropp** [comment]
yep no worries

**Comment by nblumhardt** [comment]
I think we should consider unlocking this one for 3.x 👍
