### ISSUE TITLE
Filtering for UseSerilogRequestLogging

### ISSUE THREAD

**Issue by cado1982** [serilog/serilog-aspnetcore#121]
It would be handy if I could filter messages that come from the UseSerilogRequestLogging middleware. My use case is to stop logging for my healthcheck path. I'm thinking something along the lines of:

`app.UseSerilogRequestLogging(e => e.RequestPath != "/healthcheck");`

Maybe this exists but I can't find a way to do that currently. Any ideas?

**Comment by cado1982** [comment]
I discovered that I can still use a RequestPath filter to remove the condensed logs:

`Log.Logger = new LoggerConfiguration()
                .Filter.ByExcluding((e) => e.Properties.ContainsKey("RequestPath") && e.Properties["RequestPath"].ToString() == "\"/healthcheck\"")`

Even though those logs don't contain the RequestPath property in the Properties sent to the log, they are still available in the filters:

`[10:25:20.999 INF]  HTTP GET /healthcheck responded 200 in 268.6539 ms {"RequestId": "0HLPAQ1TKES3L:00000001", "CorrelationId": null, "ConnectionId": "0HLPAQ1TKES3L"}`

**Comment by nblumhardt** [comment]
Great, thanks for following up, @cado1982 !

The text output you included (starting with `[10:...`) is based on an ["output template"](https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-plain-text) that selects only specific parts of the event to print. Behind the scenes, each event carries a whole lot of other data that you can see by e.g. switching your sink to use [JSON formatting](https://github.com/serilog/serilog-formatting-compact) (even just for the sake of seeing what's available).

If the `Filter.ByExcluding()` delegate syntax gets too much, there are two other options to try:

```csharp
    .Filter.ByExcluding(Matching.WithProperty("RequestPath", "/healthcheck"))
```

This ☝️ is the same filter as the one you've written longhand (just syntactic sugar).

Alternatively, [_Serilog.Filters.Expressions_](https://github.com/serilog/serilog-filters-expressions) enables SQL-like filters written as text:

```csharp
    .Filter.ByExcluding("RequestPath = '/healthcheck' and StatusCode < 400")
```

The latter option is easier to work with when things get more complicated :-)

Cheers!

**Comment by cado1982** [comment]
Brilliant, thanks @nblumhardt.

Serilog is awesome. I love the Matching.WithProperty syntax, it reads better than the lambda I was using. I'll use the second option you provided as I would probably want to log failures based on status code.

Keep up the good work!

**Comment by rafamartinsbr** [comment]
i was looking for a way of filtering out log entries related to static assets being served from my aspnet core mvc-app (such as .css, .js or image files)

since i've just read many threads/issues and tutorials and could not find such example, i'm sharing one here (just in case someone else is trying the same). the solution i found is based on this github issue (+serilog docs) and seems to work fine.

you can/should of course improve it and make it suitable for your requirements, but this is one way of achieving it:

one could exclude entries of "lib/" content being served (if your webapp stores your client-side dependencies under /lib folder) by adding

```
.Filter.ByExcluding("RequestPath like '/lib/%'")
```
or similarly

```
.Filter.ByExcluding("RequestPath like '/css/%'")
```
or even by file extension

```
.Filter.ByExcluding("RequestPath like '/%.png'")
```

you could of course exclude all 3 examples in one single expression
