### ISSUE TITLE
Logging caught exceptions

### ISSUE THREAD

**Issue by AistisT** [serilog/serilog-aspnetcore#14]
Is there a global way to log caught exceptions?
Sure exception might be handled locally, but it would be very useful to be able to see why it happened and what could potentially be causing it.

Uncaught exceptions are logged perfectly, but caught ones just vanish in thin void. Unless I am missing a way to implement it. 
I know it can be done manually, but manually logging each try and catch is a nightmare.

**Comment by nblumhardt** [comment]
Not the answer you're looking for :-) but I think you probably _do_ want to look at, and log, each case individually.

If exceptions are being regularly caught, should they be error-level events, or warnings, for example? Probably case-by-case; some caught exceptions won't be candidates for logging at all.

Also, when logging caught exceptions (and there may be a lot of them), including some information about what failed will be the only way to separate these into "kinds" so that they can be acted upon.

YMMV, of course, but hope this helps!

Also, you may find some value in the C# 7 exception filter mechanism, if you do still decide to take this path.

Nick

**Comment by tsimbalar** [comment]
@AistisT if you really want to log **ALL** exceptions, even the ones that are caught, you may want to look at *first chance exceptions* : https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-receive-first-chance-exception-notifications 

This allows to set handlers to be executed when *any* exception happens, even before any `try`/`catch`. Note that it will be triggered for both caught and uncaught exceptions. I believe this can be useful for debugging, but I would probably not enable that in a production environment. 

I think some dev tools like [*Stackify Prefix* ](https://stackify.com/prefix/) rely on this to show all exceptions going on in the app ... Visual Studio also allows to *break* on first-chance exception in the debugger.
