### ISSUE TITLE
ActionId/ActionName missing in UseSerilogRequestLogging

### ISSUE THREAD

**Issue by jchannon** [serilog/serilog-aspnetcore#143]
Some of the properties you see in non UseSerilogRequestLogging logging include ActionId/ActionName. When using UseSerilogRequestLogging these properties don't seem to be recorded

**Comment by nblumhardt** [comment]
Howdy! `ActionId`/`ActionName` etc. are only going to be attached to events raised _during execution of the action_ by default. ASP.NET Core pushes these onto the logger scope before executing the action, and pops them afterwards.

The default logging includes these because there are a bunch of events emitted by MVC during the request handling process.

To add them back in, try adding this filter to the MVC configuration (or applying it to controllers/actions as an attribute):

```csharp
using System;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;
using Serilog;

namespace WebApplication1
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
    public class SerilogMvcLoggingAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var diagnosticContext = context.HttpContext.RequestServices.GetService<IDiagnosticContext>();
            diagnosticContext.Set("ActionName", context.ActionDescriptor.DisplayName);
            diagnosticContext.Set("ActionId", context.ActionDescriptor.Id);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/342712/67049700-3f312400-f17a-11e9-9861-f2eef037b0a4.png)

**Comment by nblumhardt** [comment]
Wrote this up as a post: https://nblumhardt.com/2019/10/serilog-mvc-logging/

**Comment by jchannon** [comment]
Just added it! Thanks!

**Comment by nblumhardt** [comment]
Great 👍 thanks for the follow-up!
