### ISSUE TITLE
Why use this package/library/provider over the default MS Logging library/provider?

### ISSUE THREAD

**Issue by PureKrome** [serilog/serilog-aspnetcore#16]
Hi Nick,

I'm still trying to get my head around ASPNET Core 2 + Logging and how Serilog comes into play with respect to the built in MS logging provider provded by MS (for .NET Core).

The built in MS logging has a `Console` sink (which is ok for dev, but not staging/prod) and [can also handle semantic logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-message-template). It also [seems to have scoping](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-scopes) too.

So i'm trying to see where the differences lie ... mainly with respect to developers like me who need to make a choice on what logging provider to use and were to send the results to.

Is it about the available sinks and if we want to send our log out to a sink not provided by MS then we need to use a different logging provider (like Serilog) and then use _their_ sink(s) which we feel we wish to output-to.

Also, how does the effect non aspnet libraries? For example, I create a few other projects that end up being nuget packages and i have them as dependencies in my ASPNET-Core app (`nuget install-package`, etc). So far I'm using the MS ILogger cause from my package/libraries point of view, it doesn't know nor care what type of logging provider will be used Above/Outside of this package/library.

NOTE: this is a similar question to #3 but not the same IMO.

cheers!

EDIT:

Also, how does this Serilog library differ to the [Serilog.Extensions.Logging](https://github.com/serilog/serilog-extensions-logging) library?

**Comment by nblumhardt** [comment]
Howdy Mr. Krome! :-)

> Also, how does the effect non aspnet libraries?

That's partially where _Serilog.Extensions.Logging_ fits in (if you need MEL support), however, Serilog works well "standalone" on .NET Core - you don't need to do anything differently from how you'd approach using Serilog with a .NET Framework app.

> So i'm trying to see where the differences lie ... mainly with respect to developers like me who need to make a choice on what logging provider to use and were to send the results to.

The built-in provider is very basic, and has limited output options, but also:

 * Has no way to control how structured values are captured by sinks, nor support for `@` capturing of structured data
 * Has no general concept of "enrichment" separate from scope
 * Has no standard JSON output formatting, that I have seen
 * Has no concept of filtering, except by event level

Which is not to say the built-in provider is lacking, it's just not been positioned to date as a complete logging solution. It's a great starting point for ASP.NET _File > New Project_ apps, but beyond viewing the console/debug logs during early stages of development it's still very early days for it.

Have to run, but hope this quick reply helps!
NB

**Comment by PureKrome** [comment]
Hmm... I'd really love to see a side-by-side example that compares the two using sample outputs for us blondies 😊 

for example:

> Has no way to control how structured values are captured by sinks, nor support for @ capturing of structured data

I have no idea what this means :(

Also, I sit in two categories:
- library developer (e.g. I create nuget packages for developers to pull down and use/consume in their apps)
- app developer (e.g. your simple aspnet-core web app).

so as a library developer, I would like to -not assume or force- a logging framework onto my consumers. I would like to leave this up to the developer(s) who are working on their app to make that personal call. But it sounds like, if I need to advanced stuff like advanced enrichment, then this is lacking from the MSLogging so I would need Serilog (ok, fine with that example) but if I'm just going to use simple scoping and logging, could the library then use MSLogging *interface* and let the app then decide on the concrete library to end up using?

> if you need MEL support

What's MEL support?

So yeah ... I'm still sorta blond-confused :(

Does Serilog offer an extension which _uses_ the MSLogging interface stuff (in libraries that don't do hardcore logging stuff) and then _takes over_ in the app and handles the last step, which are custom sinks etc.

or is it a full 100% replacement ... it's either Serilog turtles-all-the-way-down or MSlogger (with no advanced scenario's, lacking sinks, etc).

**Comment by nblumhardt** [comment]
Thanks for the reply. I can see it would be valuable having some more information like this out there; just a matter of finding time to produce it, I guess :-)

> > Has no way to control how structured values are captured by sinks, nor support for @ capturing of structured data

> I have no idea what this means :(

When you log a value, say an instance of `Point`, Serilog lets you control whether that value will be recorded as a `ToString()` value, e.g. `"(1, 2)"`, a structure `{"X": 1, "Y":2}` or even, say, an array `[1, 2]`. The built-in provider doesn't have this kind of functionality/plumbing.

It's not something you hit immediately in small apps, but in big systems it's really common to see Serilog plug-ins like [_Destructurama.FSharp_](https://github.com/destructurama/fsharp), [_Destructurama.JsonNet_](https://github.com/destructurama/json-net) and app-specific policies.

The mention of `@` is because this is how to instruct Serilog to capture a value as a serialized object rather than as a string - see "capturing structure" in https://nblumhardt.com/2016/06/message-templates-and-properties-structured-logging-concepts-in-net-3/.

> I would like to -not assume or force- a logging framework onto my consumers. I would like to leave this up to the developer(s) who are working on their app to make that personal call. 

In that situation, LibLog is an even better option than _Microsoft.Extensions.Logging_. Check out: https://nblumhardt.com/2016/04/which-logging-abstraction-should-i-use/.

Choosing _Microsoft.Extensions.Logging_, as a library developer, _is_ forcing users into a particular framework.

> > if you need MEL support

> What's MEL support?

_Microsoft.Extensions.Logging_

> Does Serilog offer an extension which uses the MSLogging interface stuff (in libraries that don't do hardcore logging stuff) and then takes over in the app and handles the last step, which are custom sinks etc.

This repository is one of those extensions, as is _Serilog.Extensions.Logging_.

> or is it a full 100% replacement ... it's either Serilog turtles-all-the-way-down or MSlogger (with no advanced scenario's, lacking sinks, etc).

There are four basic options:

 1. Just use Serilog, forget all about MEL, and if you need to record events from ASP.NET Core etc. plug in this package just to get events from the framework -> Serilog
 1. Use the MEL interfaces, plug in this package, and use the Serilog back-end pipeline/sinks etc.
 1. Use the MEL interfaces, plug in _Serilog.Extensions.Logging_, and use the MEL pipeline with Serilog just for filling in sinks that MEL doesn't support
 1. Use MEL only

I can't make a suggestion without the appearance of bias, but numbers 1. and 4. are the happiest places right now, I think.

With option 1., you get a mature, fully-integrated, consistent, predictable logging pipeline with full support for the framework log sources.

With option 4., you get a quick/easy out of the box experience, and can probably just stick with it, as long as your needs are fairly simple.

The middle options are fine, but they have the usual lowest-common-denominator/integration compromises that come with running one logging pipeline under another's interface.

**Comment by nblumhardt** [comment]
Oh, and with Serilog, you can have VS Code-themed, syntax-highlighted console output ;-) https://nblumhardt.com/2017/06/ansi-console/

**Comment by nblumhardt** [comment]
@PureKrome did this end up covering your questions? Cheers! :-)

**Comment by PureKrome** [comment]
I think it sorta did ... but I'm still pretty much confused as when I started. The curse of being blond.

I'm trying to find some time (which could be in the Xmas break) to actually go through some of the steps above .... assuming I've grok'd each one correctly.

Basically, code talks. I need to see code differences so I can visually compare the results against each one.

I'm stuck thinking option-2 or option-3 is where I'm _trying_ to be but just got get things...

**Comment by nblumhardt** [comment]
I think the trouble with the visual comparison/"code talks", is that on the surface, both have very similar APIs. It's the functionality gap that's probably most relevant.

I might close this one because I think there's only so far a topic like this can be meaningfully explored in a threaded conversation, but it'd be cool to hear where you end up once you've worked through it. Cheers!

**Comment by PureKrome** [comment]
>I think the trouble with the visual comparison/"code talks", is that on the surface, both have very similar APIs. It's the functionality gap that's probably most relevant.

To me, that's a great example why a developer should understand which library to use! Sure, they _look_ the same (api surface, etc) but under the hoods, (A) does this but (B) does that.

> but it'd be cool to hear where you end up once you've worked through it. Cheers!

Yep, will do 👍 Right now, I'm still utterly confused and need to sit down with a colleague at work to pair program out some of this. Time, etc > this opportunity 😢

**Comment by PureKrome** [comment]
Hi @nblumhardt - I'm back once again, on this issue. On holidays now and spending 100% on trying to solve this now.

Back to the four options:

1. Use Serilog, no MEL. This is not going to be an option for me because I'm thinking of nuget libraries which anyone could use. I don't want a consumer to use my library and go 'dang, i need to now use Serilog'. (More on this below)
4. Use MEL only. Nope. can't when there's not enough sinks for me.

so this leaves me with 2 or 3.

Now to me, I'm actually happy to have my libraries use the MEL interfaces in my code. Sure this is now tying them to a framework, no different to me tying them to Serilog. I just feel that this is a bit more abstract and I guess, part of me thinks it's closer to LibLog than Serilog is - meaning it's a nice abstraction. By this i really mean => using the `interfaces` in my libraries.

So again, back to 2 or 3.

I'm totally happy with host app's (i.e. a website, or console app or some webjob or function) strongly typing to Serilog (or a competitor like NLog). To me, this is the end of the road. The top of the tree. At _some point_ you have to stop using interfaces and throw in a concrete something that uses those interfaces. So I'm totally down with using Serilog as that product 👍 

So with this in mind, I'm trying to see the differences between 2 and 3 and the pro's cons and complexities.

SAMPLE GOALS:
1. API WebApp. ASP.NET core 2. Runs on Azure Web Apps. logs to .. er .. logentries or elastic search
2. Webjobs. ASP.NET core 2 on Azure again. Logging to Logentries.
