### ISSUE TITLE
Allow customization of default properties collected by UseSerilogRequestLogging()

### ISSUE THREAD

**Issue by vhatsura** [serilog/serilog-aspnetcore#174]
I suggest to change `Elapsed` to `ElapsedMilliseconds` by the following reasons:

1. In case of using structured logging, you need to look into message to understand the value is specified in milliseconds.
2. It will be aligned with other places: `HttpClient` logs, default `AspNetCore` logs

**Comment by nblumhardt** [comment]
Hi Vadim, thanks for the suggestion.

Right now I think making this change would lead to a lot of downstream churn in monitoring systems and so-on.

I agree that the `*Milliseconds` name would be preferable given the other examples you've listed, but I think it's a ship that's already sailed at this point.

**Comment by dzmitry-lahoda** [comment]
Just bump Major version of lib. My life is miserable as all these people do name things each time differently. I am suffering.

**Comment by sungam3r** [comment]
This is nothing more than a conflict of subjective opinions. For example, I use `Elapsed` in my applications. After the change you proposed, should I suffer?

**Comment by vhatsura** [comment]
> This is nothing more than a conflict of subjective opinions. For example, I use Elapsed in my applications. After the change you proposed, should I suffer?

**Comment by nblumhardt** [comment]
Thanks for the follow-up @vhatsura 👍 

Right now I still expect the pain caused by a change (especially given that large numbers of monitoring systems work with these events) will be too great to justify it. In particular, large enterprise deployments will have many services using the old and new versions of any package concurrently, making monitoring much harder.

Given that we support customization of `MessageTemplate` already, through `RequestLoggingOptions`, it does seem that adding another option there, `Func<HttpContext, double, int, IEnumerable<LogEventProperty>> GetMessageTemplateProperties`, could be worth exploring?

It would fit in at: https://github.com/serilog/serilog-aspnetcore/blob/dev/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L88

The default would just do the same array construction that we currently do inline, but an override could substitute property names etc.

We'd document it as returning one property per property token in the supplied message template - and this would be nice and easy for consumers to check by eye.

What do you think?

**Comment by dnperfors** [comment]
Allowing customization of these properties would be the preferred way. We also rely on ElapsedInMiliseconds for our monitoring, and therefor we can't use this middleware as efficient.
