### ISSUE TITLE
Remove hard coded 500 status code for exceptions

### ISSUE THREAD

**Issue by khellang** [serilog/serilog-aspnetcore#185]
When logging exceptions, the `RequestLoggingMiddleware` hard codes 500 as the status code:

https://github.com/serilog/serilog-aspnetcore/blob/d9087b65249af4b55afd7b10c1ad10fdc605c881/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L65

There are many situations where an exception does not result in a 500 status code and those requests will be logged incorrectly.

My suggestion would be to just use `httpContext.Response.StatusCode`, but I realize that in many cases, the proper status code hasn't been set at the time of exceptions being thrown.

Maybe we can use `httpContext.Response.OnStarting` to make sure we get the correct status code before logging the exception?

Ref. https://github.com/khellang/Middleware/issues/94

**Comment by nblumhardt** [comment]
Howdy! Yah - unfortunately this is a bit tricky, there are a lot of moving parts - the exception handler in the Serilog middleware executes at the point the exception is thrown (through a `when` filter) in order to capture the log context, which isn't available later on without some tricky juggling that might be preferable to avoid.

I think your suggestion over in the other thread - reordering the middleware - is the way to go. If another piece of middleware catches an exception and transforms it into a response, I'd usually expect that middleware to log the exception (even if it is just at an informational "transforming this exception to status code x" message). Does that fit with the model `UseProblemDetails()` is using?

Cheers!

**Comment by khellang** [comment]
> If another piece of middleware catches an exception and transforms it into a response, I'd usually expect that middleware to log the exception (even if it is just at an informational "transforming this exception to status code x" message). Does that fit with the model `UseProblemDetails()` is using?

Yes, that's [exactly what it's doing](https://github.com/khellang/Middleware/blob/413abc3de5e56d8beca401e7d7ff69e40a87bf61/src/ProblemDetails/ProblemDetailsMiddleware.cs#L83-L86). I guess that's good enough in this case. When the order is swapped and the exception is transformed into a response, the request logger middleware should end up logging the correct status code anyway.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; sounds like it's as good as we'll get for now 👍 

Cheers :-)
