### ISSUE TITLE
Serilog.AspNetCore killed all log output from AspNetCore

### ISSUE THREAD

**Issue by PaulDotNet** [serilog/serilog-aspnetcore#24]
I used Serilog, Serilog.Sinks.Console, Serilog.Formatting.Compact to do logging in my .net core app. It all worked fine except for messages from AspNetCore that were printed to console. I hoped that Serilog.AspNetCore would redirect messages to my file but it only killed all output from AspNetCore. I tried changing log levels but nothing helped. Any idea where should I look?

**Comment by nblumhardt** [comment]
Hi Paul - is it possible the Serilog level is set too high? I think by default ASP.NET Core will output debug-level messages, while Serilog's default is information.

If that doesn't help, can you please post all of the logger configuration code from your app?

Cheers!

**Comment by SteveLillis** [comment]
Hi Paul,

When I've encountered this in the past it's because I've either misconfigured the Write To or forgotten it entirely.  This is an especially easy mistake to make when using `Serilog.Settings.Configuration`. 

Here's an example working configuration that successfully outputs AspNetCore logs to the console:
```
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information", // Microsoft must be at Information or lower for the logs to be visible
        "System": "Information"
      }
    },
    "WriteTo": ["Console"], // Note the array even for a single item
  }
}
```

Another important note if you are using `Serilog.Settings.Configuration` is to make sure that all of the packages you are trying to use (such as Console and Compact) have been included in the project as a nuget reference.

If Serilog is quietly failing, you can get more information by adding the following at the start of your `Main()` method:

```
Serilog.Debugging.SelfLog.Enable(System.Console.Error);
```

**Comment by PaulDotNet** [comment]
Found the problem. I did not assign logger to Log.Logger but used my own static property. Assigning logger to Log.Logger fixed the problem. As I understand UseSerilog() call assumes that default Log.Logger should be used and in my case it killed all output from AspNetCore.

**Comment by nblumhardt** [comment]
Thanks for closing the loop, Paul!~
