### ISSUE TITLE
Is there a way to get the logger to destructure complex arguments made to the rest APIs?

### ISSUE THREAD

**Issue by DanHarman** [serilog/serilog-aspnetcore#25]
i.e. right now its calling ToString on any complex object arguments, which isn't super useful. e.g.

Web.Controllers.OrdersController.Post (Mifid.Web) with arguments (["Web.Controllers.OrdersController+CreateOrderRequest"]

I was hoping it could be convinced to destructure the object?

**Comment by nblumhardt** [comment]
Hi Dan, I think that event's logged by ASP.NET Core itself; the only way to modify it would be to have `@` added to the message at the point of logging.

Destructuring arbitrary objects can be a big footgun, though - I wouldn't recommend blanket destructuring of arguments to log events like this one, since it's easy for an unexpected type to come through and serialize-the-world :-)

Cheers!
Nick

**Comment by DanHarman** [comment]
Hi Nick,

Thanks for replying, and yes you are probably right. I just need to get on with implementing ToString I think!
