### ISSUE TITLE
Better performance way of using Console Sink in readme.

### ISSUE THREAD

**Issue by darcythomas** [serilog/serilog-aspnetcore#283]
The documentation recommends using the Console logger, this is good for development but causes performance degradation in production.

In some scenarios this can cause a 100X slowdown.
It would be nice if the common case example was fast!

I would like to see the readme describing how to filter messages going to the Console sink when in production.
I would like to see if the below is the best way or if the is a better way, before contributing a readme update.

```csharp

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .Enrich.FromLogContext()
#IF DEBUG
    .WriteTo.Console()
# ENDIF
.CreateLogger();

```

Alternatively have the Console sink could have an internal `#IF DEBUG` to not log in a release build?

**Comment by nblumhardt** [comment]
Thanks for the note!

This is tough, because console logging is the perfect choice for getting started, and also for a large slice of production deployments (throughput and latency depend a lot on what is being logged, and on what platform the app is deployed). Switching off console logging in release builds is not generally desirable - especially if you're targeting Docker, where container logs are a big part of the ecosystem.

The next step up from simple `WriteTo.Console()` is `WriteTo.Async(w => w.Console())`, which addresses latency and reduces contention on the console output lock. Perhaps we could add a short section near the end of the README `## Performance considerations`, and mention this option (as well as simply turning off console logging), along with recommending `UseSerilogRequestLogging()`, avoiding `Debug()` logs in production, and not `@` serializing large objects into the log? Some of these will be general Serilog usage suggestions, but the tutorial structure of the README here does make them more likely to be seen 🤔

**Comment by sungam3r** [comment]
Check this https://github.com/manigandham/serilog-sinks-fastconsole

**Comment by nblumhardt** [comment]
I think `WriteTo.Async(w => w.Console())` will have very similar performance characteristics to `FastConsole()`, while retaining the standard console sink's theming and formatting, along with `Async()`'s queue management options.

**Comment by darcythomas** [comment]
I'll do some tests with `WriteTo.Async(w => w.Console())` and see what the performance is like.

**Comment by cremor** [comment]
Couldn't a Debug sink be used instead of the Console sink? That would automatically be disabled in release builds, so the ugly `#if DEBUG` could be avoided.

**Comment by nblumhardt** [comment]
@cremor thanks for the note; there are pros/cons, many many scenarios rely on console logging in production, and during development good console logging is also often very valuable.

I don't think this repo is the place to tackle all of the nuances of logging to stdio :-) -  I've added a short placeholder section on performance to the console sink's README:

https://github.com/serilog/serilog-sinks-console#performance

**Comment by cremor** [comment]
@nblumhardt A note in the readme of the console sink is good. But shouldn't this note also be in the readme of repositories that use the console sink in their instructions, like the ASP.NET Core package here in this repository?
