### ISSUE TITLE
Critical vulnerability reported in MINIMUM COMPATIBLE VERSION OF dependant package

### ISSUE THREAD

**Issue by robertwnorris** [serilog/serilog-aspnetcore#323]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other related package, please try to track down the correct repository for that package and create the report there: this tracker is for the  **Serilog.AspNetCore** package only.

**Description**
snyk is reporting a critical security issue on a dependent package

**Reproduction**
See image
![image](https://user-images.githubusercontent.com/3258269/233829461-b521e8f2-0fd6-4615-98ec-cc6141248737.png)

**Expected behavior**
Uses a newer version of the System.Text.Encodings.Web to avoid the issue

**Relevant package, tooling and runtime versions**
6.1.0

**Comment by robertwnorris** [comment]
Thanks for info and sorry if I caused any alarm

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nblumhardt** [comment]
Hi Robert - sorry, no - the report is fine 👍 

We're in the midst of a bit of an awkward transition whereby .NET libraries like Serilog are faced with a trade-off between providing backwards compatibility (always very strongly requested by consumers) and triggering this kind of result from tools that focus on the possibility of using insecure code, rather than what actually ends up getting installed and run as part of a real-world application.

In case you missed it though, the blue text in your screenshot says:

> **Runtime Vulnerability:** This vulnerability is probably caused by the installed .NET Framework/runtime version.

I'm assuming that you've already checked this - if not, and you're using the package on a .NET version that ships with the vulnerable DLL, you'll still have some work to do there. HTH!

**Comment by robertwnorris** [comment]
Thanks Nicholas, I'll check this

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by nblumhardt** [comment]
v7 is now out and changes our versioning strategy to avoid this issue.
