### ISSUE TITLE
Update to Serilog 3.0

### ISSUE THREAD

**Issue by twenzel** [serilog/serilog-aspnetcore#333]
Please update to Serilog 3.0

**Comment by nblumhardt** [comment]
There's no compatibility reason to update, currently; we'll definitely make that change in the future, but because Serilog v3 drops TFMs, this will need to go out with Serilog.AspNetCore 8.0 in November.

I'll close this as updating dependencies is a usual part of the release process and we won't need to track it separately. Thanks!
