### ISSUE TITLE
Best place to configure logging with access to IOptions?

### ISSUE THREAD

**Issue by tmenier** [serilog/serilog-aspnetcore#39]
I'm using this package along with Serilog.Sinks.AzureDocumentDB. I'm also using the [Options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options) to inject a strongly-typed `AppSettings` instance where I need it. This contains, among other things, the DocumentDB URI and key needed to connect for logging.

I'd like to be able to configure Serilog _somewhere_ that I have access to a container-injected services so I can get at my `AppSettings` instance, but I can't do that in `Program.Main` where you recommend doing this configuration. It's sort of a chicken-and-egg problem.

Any suggestions? Thanks in advance!

**Comment by nblumhardt** [comment]
I think the best option here is probably to forego `IOptions` and just retrieve the URI by name from the configuration - there's a bigger trade-off IMO if you switch to constructing the logger via IoC, because you can no longer log exceptions raised by your IoC container at start-up (or by constructors called by the container at start-up). Chicken and egg :-)

**Comment by tmenier** [comment]
That makes sense, thanks. At least the trade-off is clear.
