### ISSUE TITLE
Consider Adding a LogAndRun Extension Method to IWebHost

### ISSUE THREAD

**Issue by RehanSaeed** [serilog/serilog-aspnetcore#4]
I wrote the following extension method to remove a bunch of boilerplate that I kept having to write.

```
public static int LogAndRun(this IWebHost webHost, Logger logger)
{
    Log.Logger = logger;

    try
    {
        Log.Information("Starting application");
        webHost.Run();
        Log.Information("Stopped application");
        return 0;
    }
    catch (Exception exception)
    {
        Log.Fatal(exception, "Application terminated unexpectedly");
        return 1;
    }
    finally
    {
        Log.CloseAndFlush();
    }
}

public static void Main(string[] args) => WebHost
    .CreateDefaultBuilder()
    .Build()
    .LogAndRun(
        new LoggerConfiguration()
            .MinimumLevel.Debug()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .CreateLogger());
```

**Comment by nblumhardt** [comment]
Thanks for the suggestion 👍 

Until we've got a bit more of a feel for the direction this project is headed, I think we should hold off on adding much, but in the future this seems like a direction we might explore.

The parameter to `LogAndRun()` should probably be `Logger`, rather than `ILogger`, if the method is going to manage the lifetime of the pipeline (passing e.g. a contextual `ILogger` wouldn't achieve the desired result with `CloseAndFlush()`).

**Comment by nblumhardt** [comment]
Closing this one as I think it would lead to issues of the kind reported in #10
