### ISSUE TITLE
How are we supposed to unit test?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [serilog/serilog-aspnetcore#70]
the class `Log` is not abstract neither it implements an interface... is there a OOB way to test code being monitored with serilog? or i should start creating wrappers?

**Comment by tsimbalar** [comment]
There are several approaches : 

- you can either choose not to use the static `Log` class (`Log.Logger` etc ... ) and instead inject the `ILogger` instead (then it's easy to use a mock or a fake or whatever you want)
- you can set `Log.Logger` to an `ILogger` of your choice before your test , and look at the emitted events in there. You might experience strange behaviors if you have tests running in parallel though.

Not sure if that helps, but this repo by @damianh also details how to capture logs with XUnit : https://github.com/damianh/CapturingLogOutputWithXunit2AndParallelTests

I usually try to avoid wrapping everything in wrappers, because it kind of prevents you from learning the Serilog APIs :P

**Comment by nblumhardt** [comment]
There's also: https://github.com/Microsoft/serilog-sinks-testcorrelator - HTH!

**Comment by damianh** [comment]
Nice alternative there

**Comment by tsimbalar** [comment]
See also question : https://github.com/serilog/serilog/issues/703

**Comment by manjunathdl66** [comment]
> There are several approaches :
> 
> * you can either choose not to use the static `Log` class (`Log.Logger` etc ... ) and instead inject the `ILogger` instead (then it's easy to use a mock or a fake or whatever you want)
> * you can set `Log.Logger` to an `ILogger` of your choice before your test , and look at the emitted events in there. You might experience strange behaviors if you have tests running in parallel though.
> 
> Not sure if that helps, but this repo by @damianh also details how to capture logs with XUnit : https://github.com/damianh/CapturingLogOutputWithXunit2AndParallelTests
> 
> I usually try to avoid wrapping everything in wrappers, because it kind of prevents you from learning the Serilog APIs :P

Could you please elaborate injecting ILOGGER in testing project using Serilog

**Comment by roger-wernersson** [comment]
I deliberately wrap SeriLog to be able to be able to switch logger when I want to.

I want to test my wrapper though.
