### ISSUE TITLE
Serilog With Azure Api App

### ISSUE THREAD

**Issue by markgmarkg** [serilog/serilog-aspnetcore#8]
Hi,

I've integrated Serilog into WebApi project developed with Asp.Net Core 2.0
This is the configuration code in `Program.cs`:
```
Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .CreateLogger();
```
I manage to see the logs during the debug perfectly.

I deploy the service in Azure as API app.
How can I see the logs in the production environment through Log Stream extension in Azure Portal?

Thank you :)

**Comment by nblumhardt** [comment]
Hi @markgmarkg - there's scant information available about this online, it seems, but I think there's a good chance https://github.com/serilog/serilog-sinks-trace will get you there. Let me know if it works! :-)

**Comment by cnelsonak** [comment]
@nblumhardt - I have been working on this the same thing and it does not appear that https://github.com/serilog/serilog-sinks-trace is enough to get Serilog to log to either the filesystem/log stream or blobs with Application Logging turned on in Diagnostic Logging. Any chance we can re-open this or update to reflect how one might use Application Logging and Seriolog together with an Asp.Net Core application deployed to Azure?

**Comment by nblumhardt** [comment]
Thanks for the nudge @cnelsonak - I think the info here is what you need: https://github.com/serilog/serilog-aspnetcore#writing-to-the-azure-diagnostics-log-stream

**Comment by cnelsonak** [comment]
@nblumhardt Thanks for the response. I was able to get the Diagnostics Log Stream to display events using the info in the link you provided. But that doesn't appear to be the same as getting those events to write to the actual Application Log -- it is similar I think because it can be used for Log Streaming, but it doesn't get those events to appear in a Storage Blob when that is enabled for the Application logs. I'm really trying to get the events to the Blob since that can be managed and the retention can be guaranteed. It appears writing to the file system in Azure as detailed in the link above has limitations on size and rotation that cannot be configured nor guaranteed for retention.
